language: cpp

compiler:
  - gcc
  - clang
  
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libboost-dev
  
script: 
  - ./build.py -c -b Debug
  - ./build.py -c -b Release
  - ./build.py -c -b RelWithDebInfo
  

notifications:
  recipients:
    - calebwherry@gmail.com
  email:
    on_success: change
    on_failure: always