environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"

# Branches to build:
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# Init:
init:
  - "echo %PYTHON%"
 
# Install:
install:
  - "%PYTHON%/Scripts/pip3.exe" install colorama

# Build:
build_script:
  - cmd: example-run-Win-VS2015.bat
  - cmd: "%PYTHON%/python.exe" build.py -c -b Debug
  - cmd: "%PYTHON%/python.exe" build.py -c -b Release
  - cmd: "%PYTHON%/python.exe" build.py -c -b RelWithDebInfo
  - cmd: "%PYTHON%/python.exe" build.py -c -b MinSizeRel